[package]
name = "optimization"
version = "0.1.0"
edition = "2024"

[dependencies]
argmin = "0.11"
argmin-math = { version = "0.5", features = ["ndarray_v0_16"] }
ndarray = "0.16"
ndarray-linalg = { version = "0.17", features = ["openblas-system"] }
